version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    # Remove ports to not expose directly

  database:
    image: mariadb:latest
    container_name: mariadb-container
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    container_name: backend-container
    env_file:
      - .env
    # Remove ports to not expose directly
