version: '3'
services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend-container
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mariadb:latest
    container_name: mariadb-container
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

