version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    # Remove ports to not expose directly

  database:
    image: postgres:latest
    container_name: psql-container
    environment:
      POSTGRES_DB: groovy
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./backend/prisma/migrations/20231206125317_init/migration.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    container_name: backend-container
    env_file:
      - .env
    # Remove ports to not expose directly
